name = "wgu-edgetunnel-independent"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "a6445b851b544a8cbf354e4890394045"

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id
